SisVest.WebUI/Controllers/VestibularController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SisVest.DomainModel.Abstract;
using SisVest.DomainModel.Entities;
using SisVest.WebUI.Infraestrutura.Provider.Abstract;

namespace SisVest.WebUI.Controllers
{
    //[Authorize]
    public class VestibularController : Controller
    {
        private IVestibularRepository repository;
        private IAutenticacaoProvider autenticacaoProvider;

        /// <summary>
        /// O construtor instancia e assim faz a inversão de controle para ser usado em todas as ações.
        /// </summary>
        /// <param name="cursoRepository"></param>
        public VestibularController(IVestibularRepository vestibularRepository, IAutenticacaoProvider autenticacaoProviderParam)
        {
            repository = vestibularRepository;
            autenticacaoProvider = autenticacaoProviderParam;
        }

        //[Authorize] Pode ser colocado aqui barrando só esta action 
        //ou direto lá em cima barrando todo o controller
        public ActionResult Index()
        {
            if (!(autenticacaoProvider.Autenticado && autenticacaoProvider.UsuarioAutenticado.Grupo == "administrador"))
                HttpContext.Response.StatusCode = 401;
            return View(repository.Vestibulares.ToList());
        }

        //[Authorize]
        public ActionResult Alterar(int id)
        {
            if (!(autenticacaoProvider.Autenticado && autenticacaoProvider.UsuarioAutenticado.Grupo == "administrador"))
                HttpContext.Response.StatusCode = 401;
            return View(repository.Vestibulares.Where(v => v.iVestibularId == id).FirstOrDefault());
        }
        
        [HttpPost]
        public ActionResult Alterar(Vestibular vestibular)
        {
            if (ModelState.IsValid)
            {
                repository.Alterar(vestibular);
                TempData["Mensagem"] = "Vestibular alterado com sucesso.";
                //return View("Index", cursoModel.RetornarTodos());
                return RedirectToAction("Index");
            }
            return View(vestibular);
        }

        //[Authorize]
        public ActionResult Excluir(int id)
        {
            if (!(autenticacaoProvider.Autenticado && autenticacaoProvider.UsuarioAutenticado.Grupo == "administrador"))
                HttpContext.Response.StatusCode = 401;
            return View(repository.Vestibulares.Where(v => v.iVestibularId == id).FirstOrDefault());
        }

        [HttpPost]
        public ActionResult Excluir(Vestibular vestibular)
        {
            try
            {
                repository.Excluir(vestibular.iVestibularId);
                TempData["Mensagem"] = "Vestibular excluído com sucesso.";
            }
            catch (Exception ex)
            {
                TempData["Mensagem"] = ex.Message;
            }
            //return View("Index", cursoModel.RetornarTodos());
            return RedirectToAction("Index");
        }

        //[Authorize]
        public ActionResult Inserir()
        {
            if (!(autenticacaoProvider.Autenticado && autenticacaoProvider.UsuarioAutenticado.Grupo == "administrador"))
                HttpContext.Response.StatusCode = 401;
            // Para validação Assincrona! Passa-se um iVestibularId = 0 para o JS não achar que o 
            //campo iVestibularId esteja vazio já que o iVestibularId irá ser criado pelo BD!
            var vestibular = new Vestibular { iVestibularId = 0 };
            return View(vestibular);

            // Para validação Sincrona!
            //return View(); 
        }

        [HttpPost]
        public ActionResult Inserir(Vestibular vestibular)
        {
            //Isto serve para tirar o iVestibularId da validação pois ele é inserido automáticamente pelo banco. (Validação Sincrona!)
            ModelState["iVestibularId"].Errors.Clear();
            if (ModelState.IsValid)
            {
                try
                {
                    repository.Inserir(vestibular);
                    TempData["Mensagem"] = "Vestibular inserido com sucesso.";
                }
                catch (Exception ex)
                {
                    TempData["Mensagem"] = ex.Message;
                }

                //return View("Index", cursoModel.RetornarTodos());
                return RedirectToAction("Index");
            }
            return View(vestibular);
        }
        
    }
}

SisVest.WebUI/Views/Vestibular/Alterar.cshtml
@model SisVest.DomainModel.Entities.Vestibular
@{
    ViewBag.Title = "Alterar Vestibular";
}
<h2>Alterar Vestibular</h2>
@using (@Html.BeginForm())
{
    //Assim (false) eu tiro a validação assincrona e deixo ele sincrona só nesta View sem necessidade
    //de mudar nada no Web.config
    //Isto pode ser feito também no Controller, mas aí eu tenho que por estes 2 comandos
    //nas duas Actions!

    //HtmlHelper.ClientValidationEnabled = false;
    //HtmlHelper.UnobtrusiveJavaScriptEnabled = false;    

    @Html.EditorForModel()
    <p>
    <input type="submit" value="Alterar" />
    </p>    
}

<script type="text/javascript">
    $('#dtInicioInscricao').datepicker();
    $('#dtFimInscricao').datepicker();
    $('#dtProva').datepicker();
</script>

SisVest.WebUI/Views/Vestibular/Excluir.cshtml
@model SisVest.DomainModel.Entities.Vestibular
@{
    ViewBag.Title = "Excluir";
}
<h2>
    Excluir Vestibular</h2>
<!-- Aqui o BeginForm precisa declarar action, controller, model por estar usando o 
Html.DisplayForModel(), com o @Html.EditorForModel() do anterar isto não é necessário -->
@using (@Html.BeginForm("Excluir","Vestibular", Model))
{

    @Html.DisplayForModel()
    <p>
        <input type="submit" value="Excluir" />
    </p>    
}

SisVest.WebUI/Views/Vestibular/Index.cshtml
@model IList<SisVest.DomainModel.Entities.Vestibular>
@{
    ViewBag.Title = "Index";
}
<h2>Lista de Vestibulares</h2>
<p>
    @Html.ActionLink("Inserir Novo Vestibular", "Inserir")
</p>
@{
    var grid = new WebGrid(source: Model, rowsPerPage: 3);
}
@grid.GetHtml(
    tableStyle: "grid",
    headerStyle: "header",
    footerStyle: "footer",
    columns: grid.Columns(
    grid.Column("sDescricao", header: "Vestibular"),
    grid.Column("dtInicioInscricao", header: "Inicio Iscrição", format: @<text>@item.dtInicioInscricao.ToString("dd/MM/yyyy")</text>),
    grid.Column("dtFimInscricao", header: "Fim Inscritção", format: @<text>@item.dtFimInscricao.ToString("dd/MM/yyyy")</text>),
    grid.Column("dtProva", header: "Data da Prova", format: @<text>@item.dtProva.ToString("dd/MM/yyyy")</text>),
    grid.Column(header: "Editar", format: (itemDoController) => @Html.ActionLink("Alterar", "Alterar", new { id = itemDoController.iVestibularID }), canSort: false),
    grid.Column(header: "Excluir", format: (itemDoController) => @Html.ActionLink("Excluir", "Excluir", new { id = itemDoController.iVestibularID }), canSort: false)
    )
)

SisVest.WebUI/Views/Vestibular/Inserir.cshtml
@model SisVest.DomainModel.Entities.Vestibular
@{
    ViewBag.Title = "Inserir Vestibular";
}
<h2>Inserir Vestibular</h2>
@using (@Html.BeginForm())
{
    //Assim (false) eu tiro a validação assincrona e deixo ele sincrona só nesta View sem necessidade
    //de mudar nada no Web.config
    //Isto pode ser feito também no Controller, mas aí eu tenho que por estes 2 comandos
    //nas duas Actions!

    //HtmlHelper.ClientValidationEnabled = false;
    //HtmlHelper.UnobtrusiveJavaScriptEnabled = false;

    @Html.EditorForModel()
    <p>
    <input type="submit" value="Inserir" />
    </p>    
}

<script type="text/javascript">
    $('#dtInicioInscricao').datepicker();
    $('#dtFimInscricao').datepicker();
    $('#dtProva').datepicker();
</script>